title: Anylinux AppImages
description: AppImages that run on any Linux distribution
baseurl: "/Anylinux-AppImages"
url: "https://xlc-dev.github.io"

markdown: kramdown
highlighter: rouge

exclude:
  - useful-tools/
  - .github/
