name: Build Demos
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    paths-ignore: [ '**/*.md' ]
  schedule:
    - cron: "0 7 1/14 * *"
  workflow_dispatch: {}

jobs:
  build:
    name: "${{ matrix.script }} (${{ matrix.arch }})"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - arch: x86_64
            platform: linux/amd64
            runs-on: ubuntu-24.04
            script: vkcube-glxgears-appimage
          - arch: aarch64
            platform: linux/amd64
            runs-on: ubuntu-24.04-arm
            script: vkcube-glxgears-appimage
          - arch: x86_64
            platform: linux/amd64
            runs-on: ubuntu-24.04
            script: gtk3-demo-appimage
          - arch: aarch64
            platform: linux/amd64
            runs-on: ubuntu-24.04-arm
            script: gtk3-demo-appimage
          - arch: x86_64
            platform: linux/amd64
            runs-on: ubuntu-24.04
            script: gtk4-demo-appimage
          - arch: aarch64
            platform: linux/amd64
            runs-on: ubuntu-24.04-arm
            script: gtk4-demo-appimage
          - arch: x86_64
            platform: linux/amd64
            runs-on: ubuntu-24.04
            script: qt6-dbus-demo-appimage
          - arch: aarch64
            platform: linux/amd64
            runs-on: ubuntu-24.04-arm
            script: qt6-dbus-demo-appimage
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
      - uses: actions/checkout@v4

      - name: Make AppImage
        run: sh ./useful-tools/demo/${{ matrix.script }}.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: AppImage-${{ matrix.arch }}-${{ matrix.script }}
          path: dist

  release:
    if: ${{ github.ref_name == 'main' }}
    needs: [build]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.3.0
        with:
          pattern: AppImage-*
          merge-multiple: true

      - name: Release Artifacts
        uses: softprops/action-gh-release@v2.5.0
        with:
          name: "demos"
          tag_name: "demo"
          prerelease: false
          draft: false
          generate_release_notes: false
          make_latest: true
          files: |
            *.AppImage
